version: '2'

services:

  jupyter:
    build: jupyter/
    volumes:
      - ./notebooks:/notebooks
      - ./input:/input
      - ./output:/output
    ports:
      - "8888:8888"
    networks:
      - tf

networks:

  tf:
    driver: bridge
